# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Archive accounts

on:
  push:
    branches: [ "main" ]

  schedule:
    - cron: 0 0 * * 0,2,4,6

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        handle:
          - spearcat.bsky.social
          - lunabuna.sisters.moe

    name: Make snapshot of ${{ matrix.handle }}
    
    steps:
    - uses: actions/checkout@v4
  
    - uses: gautamkrishnar/keepalive-workflow@v2

    - uses: pnpm/action-setup@v4
      with:
        version: 10.0.0-beta.1+sha512.629de0531b9ae9a3f8e372d014ef8f5a57906d9a48095ced54bbfbd246b4136381478032c8d13819fd1eedde8330517a799ea6756eedd9a136e36524fa3083cf

    - run: pnpm install

    - run: pnpx tsx src/index.ts
      env:
        BACKUP_HANDLE: ${{ matrix.handle }}
        BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        USE_ACTIONS: 1
        GITHUB_TOKEN: ${{ github.token }}
