# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

  schedule:
    - cron: 0 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - uses: gautamkrishnar/keepalive-workflow@v2

    - uses: pnpm/action-setup@v4
      with:
        version: 10.0.0-beta.1
    - run: pnpm install

    - run: pnpx tsx src/index.ts
      env:
        BACKUP_HANDLE: lunabuna.sisters.moe
        BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        USE_ACTIONS: 1
        GITHUB_TOKEN: ${{ github.token }}

    - run: pnpx tsx src/index.ts
      env:
        BACKUP_HANDLE: spearcat.bsky.social
        BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        USE_ACTIONS: 1
        GITHUB_TOKEN: ${{ github.token }}
